# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b488e3c34571301e54ea86b1e1c810ff769a34d30090e0546949e861de3b82cffd1bea39d45cab136fb7476e3e9be7fa2a2d5e8efa55fb600283ba13c07c8077

test:
  secret_key_base: 747a2a1da5340df3d512902f5980ae6e763ce37efdc386a8b42f00f33d3cd927ae98141bb1b07fef00ed5eda6530549decb276bdba581dbd0a6fcd4716dfb5e4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
